model: "fno3d"
modes1: [8, 8, 8, 8, 8, 8, 8, 8]
modes2: [8, 8, 8, 8, 8, 8, 8, 8]
modes3: [8, 8, 8, 8, 8, 8, 8, 8]
layers: [64, 64, 64, 64, 64, 64, 64, 64, 64]
activate_last_layer: True
mollifier: 0.005
fc_dim: 256
out_dim: 64
activation: "gelu"
constraint:
  system: "levenbergmarquardt"
  num_sampled_points: 20000
  mask_boundary_conditions: true
